#!/bin/sh

SYSTEM_USER_NAME=$(id -un)
if [[ "${SYSTEM_USER_NAME}" == 'root'  ]]
then
    echo "Ne doit pas être exécuté en tant que root. Passez utilisateur"
    exit 1
fi

echo "Arrêt de portainer..."
docker container stop portainer